### ISSUE TITLE
Problem with Template#extract

### ISSUE THREAD

**Issue by jfitisoff** [sporkmonger/addressable#164]
The following example is from README.md and seems to be failing with 2.3.6. It does seem to work when I try 2.2.8. Am rolling back to 2.2.8 for now...

johns-mbp:test john$ ruby -v
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]
johns-mbp:test john$ pry
[1] pry(main)> require 'addressable/uri'
=> true
[2] pry(main)> require 'addressable/template'
=> true
[3] pry(main)> template = Addressable::Template.new(
[3] pry(main)*   "http://{host}{/segments}/{?one,two,bogus}{#fragment}"  
[3] pry(main)* )  
=> #<Addressable::Template:0x3fcb77b4b950 PATTERN:http://{host}{/segments}/{?one,two,bogus}{#fragment}>
[4] pry(main)> uri = Addressable::URI.parse(
[4] pry(main)*   "http://example.com/a/b/c/?one=1&two=2#foo"  
[4] pry(main)* )  
=> #<Addressable::URI:0x3fcb77b5da4c URI:http://example.com/a/b/c/?one=1&two=2#foo>
[5] pry(main)> template.extract(uri)
=> nil
[6] pry(main)> Gem.loaded_specs['addressable'].version
=> Gem::Version.new("2.3.6")

**Comment by therabidbanana** [comment]
Sorry all - I think Google has just permanently blackholed my Github notifications to those gmail tabs I never look at any more. I just noticed a recent addressable release and realized I should check in... 

In any case - @jure is correct, this is a typo in the readme, I probably fat fingered it while copy-pasting some of the specs into the readme. {/segments} cannot possibly match /a/b/c without list expansion. (just noticing /a,b,c should match, however - that's a separate bug - #184 )  Looks like #170 won't merge cleanly - but I cherry-picked into a fresh branch.

**Comment by jure** [comment]
No worries, @therabidbanana, thanks for the cherry-pick! Can you close this issue once the commit is merged to sporkmonger/addressable?

**Comment by jure** [comment]
Thanks for the merge! :cake:
