### ISSUE TITLE
Require 'addressable/uri' automatically

### ISSUE THREAD

**Issue by conf** [sporkmonger/addressable#168]
Basically, the question is taken from this [stackoverflow question](http://stackoverflow.com/questions/12497138/addressable-gem-is-not-found), i.e. if I have `addressable` in my Gemfile
```ruby
gem 'addressable'
```
I also have to explicitly `require 'addressable/uri'` in order to use `Addressable::URI`. 
Can we get rid of this extra step? Thank you.

**Comment by sporkmonger** [comment]
The main reason I did it this way was because there is also `Addressable::Template`, and most people who want `Addressable::URI` do not need `Addressable::Template`. But I suppose there's no reason you couldn't separately load them since the top-level require can be optional.

**Comment by conf** [comment]
Well, maybe it will be better to move out `Addressable::Template` to its own gem and make `addressable` depend on it? This way it would be more SRP and people who want only `Addressable::Template` would use that gem only.
