### ISSUE TITLE
Documented return type is not the same as actual return type for Addressable::URI#query_values

### ISSUE THREAD

**Issue by scooter-dangle** [sporkmonger/addressable#172]
I was relying on the reported return type in the documentation (https://github.com/sporkmonger/addressable/blob/master/lib/addressable/uri.rb#L1503) and getting `NoMethodError` when trying to do
```ruby
request_uri = Addressable::URI.parse(request_url)
if request_uri.query_values['a_param']  # NoMethodError here due to #query_values returning nil rather than a Hash
  # do stuff
end
```
It would help if either the documentation were changed to include `nil` as a return value for `query_values` or if the line (at https://github.com/sporkmonger/addressable/blob/master/lib/addressable/uri.rb#L1517)
```ruby
  return nil if self.query == nil
```
were changed to
```ruby
  return empty_accumulator if self.query == nil
```
since `empty_accumulator` will be an instance of the class requested by the user.

I would personally prefer that an empty instance of the provided class be returned, but changing the documentation would at least fix the issue without possibly breaking any code that currently relies upon a `nil` return value.

**Comment by djberg96** [comment]
I'm late to the party, but I would have preferred an empty instance as well. In my case, I'm having to do this:

    nested = (uri.query_values(Array) || []).sort
