### ISSUE TITLE
Parsing URI with ambiguous path returns InvalidURIError instead of raising it

### ISSUE THREAD

**Issue by RST-J** [sporkmonger/addressable#177]
When a string which is identified to have an ambiguous path is parsed with ```addressable 2.3.6``` (checked with Ruby 2.1.0 and 2.1.3) the corresponding error is returned, not raised:
```ruby
require 'addressable/uri'

a = Addressable::URI.parse('http:')
# raises Addressable::URI::InvalidURIError: Absolute URI missing hierarchical segment: 'http:'
# a == nil

b = Addressable::URI.parse('::boo')
# raises nothing but returns Addressable::URI::InvalidURIError
# hence, b holds a Addressable::URI::InvalidURIError
```
I would expect the error to also be raised in the second case. Is this intended behaviour or a bug?

**Comment by sporkmonger** [comment]
Woah, that's a hilarious bug. Wow.

**Comment by sporkmonger** [comment]
Oh, I see, issue description is slightly incorrect. What's actually happening is that an `Addressable::URI` instance is returned in `b`, but the error occurs in the `inspect` method, which gives the appearance that an exception instance has been returned.
