### ISSUE TITLE
Incorrectly marking a bad url as good

### ISSUE THREAD

**Issue by twiz718** [sporkmonger/addressable#178]
2.1.2 :002 > x = Addressable::URI.parse("http://www.techbargains.comhttp://images10.newegg.com/uploadfilesfornewegg/rebate/sh/newegg/hp2mirs_59336oct30dec3114yh62.pdf")
 => #<Addressable::URI:0x2dd848c URI:http://www.techbargains.comhttp//images10.newegg.com/uploadfilesfornewegg/rebate/sh/newegg/hp2mirs_59336oct30dec3114yh62.pdf> 
2.1.2 :003 > x.host
 => "www.techbargains.comhttp"

**Comment by sporkmonger** [comment]
This is a valid URI according to the URI specification. As a human being, you can tell that something else was intended, but that doesn't make this an invalid URI.

**Comment by sporkmonger** [comment]
It's worth noting though, that if you are accepting URIs from user input, the correct method to call is `heuristic_parse`, not `parse`.
