### ISSUE TITLE
Return a default port instead of nil if no port part in URI

### ISSUE THREAD

**Issue by glebtv** [sporkmonger/addressable#179]
Currently:

    > Addressable::URI.parse('http://test.ru').port
    => nil

Ruby's default URI does this:

    > URI.parse('http://test.ru').port
    => 80
    > URI.parse('https://test.ru').port
    => 443

**Comment by sporkmonger** [comment]
There's `port` and `inferred_port`. What you want is `inferred_port` in this case.
