### ISSUE TITLE
No method error

### ISSUE THREAD

**Issue by mg786** [sporkmonger/addressable#181]
I keep getting 'private method 'URI' called for Addressable::Module <NoMethodError>' when i try to use addressable in one of project areas, however it is working fine in different areas.

I cant post the code as it is for work, but I was wondering if you knew a reason why this could be happening?

**Comment by sporkmonger** [comment]
That's a tough one without code, but it could be a load order issue of some kind. Try putting an explicit `require 'addressable/uri'` a little bit earlier in your application startup.
