### ISSUE TITLE
Apparently invalid URI parses

### ISSUE THREAD

**Issue by iainbeeston** [sporkmonger/addressable#187]
I recently discovered that addressable will parse `'{"a": 1, "b": 2}'` as a URI:

    > Addressable::URI.parse('{"a": 1, "b": 2}').scheme
    => "{\"a\""
    > Addressable::URI.parse('{"a": 1, "b": 2}').path
    => " 1, \"b\": 2}"

For comparison, Ruby's URI class will not parse it:

    > URI.parse('{"a": 1, "b": 2}')
    URI::InvalidURIError: bad URI(is not URI?): {"a": 1, "b": 2}
	from /Users/iain/.rubies/ruby-2.2.1/lib/ruby/2.2.0/uri/rfc3986_parser.rb:66:in `split'
	from /Users/iain/.rubies/ruby-2.2.1/lib/ruby/2.2.0/uri/rfc3986_parser.rb:72:in `parse'
	from /Users/iain/.rubies/ruby-2.2.1/lib/ruby/2.2.0/uri/common.rb:226:in `parse'
	from (irb):14
	from /Users/iain/.rubies/ruby-2.2.1/bin/irb:11:in `<main>'

I realise that the rfcs for URIs are very flexible, but this seems a bit extreme, and I thought I'd flag it up in case this is a valid bug.

**Comment by sporkmonger** [comment]
Not actually a valid bug, amazingly. There's a ton of stuff that's very clearly not *intended* to be a URI that is in fact validly parseable as one. This is an extreme example, but an example nonetheless.
