### ISSUE TITLE
HOST accepts comma chars

### ISSUE THREAD

**Issue by nandosousafr** [sporkmonger/addressable#198]
I noticed that `Addressable::URI.parse` do not take `'http://www,google.com'` as invalid, behavior which I was expecting.

Is that correct?

Thanks in advance!

**Comment by sporkmonger** [comment]
Yup, according to the RFC (but probably not DNS), that's correct. Addressable does not currently consider DNS in validating a URI, something that was a core motivation for writing Addressable in the first place. Per the comment on twingly/twingly-uri#74, I'm considering a `sane?` method that would consider things like valid DNS hostnames.

**Comment by dentarg** [comment]
> Per the comment on twingly/twingly-uri#74

Just to connect the issues (because of the typo above), here is a link to the comment: https://github.com/twingly/twingly-url/issues/74#issuecomment-226334749

**Comment by sporkmonger** [comment]
This handling was updated in f032606, but since commas are in `sub-delims`, they're still valid in a hostname. Closing this.
