### ISSUE TITLE
Addressable::IDNA.to_unicode does not work if there is no subdomain

### ISSUE THREAD

**Issue by volkert** [sporkmonger/addressable#199]
Addressable::IDNA.to_unicode does not encode properly if the domain does not have a subdomain.
See the following example:

```ruby
> require "addressable/uri"
 => true
2.1.6 :002 > Addressable::IDNA.to_unicode 'http://www.xn--jobbrse-d1a.com/'
 => "http://www.jobbörse.com/"
2.1.6 :003 > Addressable::IDNA.to_unicode 'http://xn--jobbrse-d1a.com/'
 => "http://xn--jobbrse-d1a.com/"
```

The problem is in https://github.com/sporkmonger/addressable/blob/c0f296f541b8ab89f41456bcd0d7628ec9fe57a7/lib/addressable/idna/pure.rb#L94 where the domain is splitted by . and then in L96 it checks if the part starts with 'xn--' but that's not the case if there is no subdomain. In that case the part starts with http://.

Unfortunately I can't provide a PR right now.

**Comment by dentarg** [comment]
@volkert a workaround could be

```ruby
[19] pry(main)> Addressable::URI.parse("http://xn--jobbrse-d1a.com/").display_uri.to_s
=> "http://jobbörse.com/"
```

**Comment by sporkmonger** [comment]
So this isn't so much a bug as it is a misuse of the library. The `to_unicode` method expects a host component only, not an entire URI.

This is the correct usage of that method:
```ruby
Addressable::IDNA.to_unicode 'xn--jobbrse-d1a.com'
# => "jobbörse.com"
```

If you want to do this for an entire URI, then what @dentarg said is what you want. And that's not a workaround, that's the correct thing to be doing.
