### ISSUE TITLE
Does not support `scp like` url used as GIT URL

### ISSUE THREAD

**Issue by cybertk** [sporkmonger/addressable#201]
Given a `scp like` url, when parsed by **Addressable**, it failed like following

```
# Addressable
url = Addressable::URI.parse('git@github.com:cybertk/git-copy.git')
url.path #=> "cybertk/git-copy.git"
url.scheme #=> "git@github.com"

url.host #=> nil
url.userinfo #=> nil
url.user #=> nil
url.port #=> nil
```

`url.host` should be `github.com` and `url.scheme` may be ssh or something acceptable.

**Comment by sporkmonger** [comment]
Well, that's kinda because SCP doesn't actually use URIs at all. There's been a few proposals for registering an SCP URI scheme, but far as I know, it's never gotten any real traction. For now, Addressable cannot be used to parse an SCP string, and doing so is out-of-scope.
