### ISSUE TITLE
Circular dependency with Launchy

### ISSUE THREAD

**Issue by alexcoco** [sporkmonger/addressable#204]
@sporkmonger 

I was getting some bundler errors after adding the `launchy` gem to my `Gemfile`. They may have been caused by a [circular dependency](https://github.com/copiousfreetime/launchy/blob/master/launchy.gemspec#L31) between `addressable` and `launchy`.

It looks like `addressable` uses `launchy` in [one place](https://github.com/sporkmonger/addressable/blob/c0f296f541b8ab89f41456bcd0d7628ec9fe57a7/tasks/rspec.rake#L12-L13). The problem might be related to https://github.com/bundler/bundler/issues/2813 and https://github.com/bundler/bundler/issues/3692.

**Comment by sporkmonger** [comment]
@alexcoco Both of those issues have been closed. Is this still causing problems for you?

**Comment by alexcoco** [comment]
I actually don't remember what I was working on at the time 😅 I tried reproducing with a minimal gemspec but could not reproduce and issues.

```ruby
  spec.add_dependency "launchy"
  spec.add_dependency "addressable"
```

I'll go ahead and close this!

**Comment by sporkmonger** [comment]
Yay! 😄
