### ISSUE TITLE
Address with port spec and without scheme causes "Invalid scheme format"

### ISSUE THREAD

**Issue by Holek** [sporkmonger/addressable#208]
This is a complete investigation after using #207.
One cannot pass an IP address or hostname without a scheme, but with a port specified to `match`.

This approach is currently used by webmock:
* https://github.com/bblimke/webmock/blob/8b3175440a260f9d23d433d0fa4e7ee9c4413d97/lib/webmock/util/uri.rb#L36-L55
* https://github.com/bblimke/webmock/blob/8b3175440a260f9d23d433d0fa4e7ee9c4413d97/lib/webmock/util/uri.rb#L81-L86

```
irb> Addressable::Template.new("http://google.com").match "127.0.0.1/event"
=> nil
irb> Addressable::Template.new("http://google.com").match "127.0.0.1:80/event"
Addressable::URI::InvalidURIError: Invalid scheme format: 127.0.0.1
from /addressable-edf55d64176e/lib/addressable/uri.rb:866:in `scheme='

irb> Addressable::Template.new("google.com").match "127.0.0.1/event"
=> nil

irb> Addressable::Template.new("google.com").match "127.0.0.1:80/event"
Addressable::URI::InvalidURIError: Invalid scheme format: 127.0.0.1
from /addressable-edf55d64176e/lib/addressable/uri.rb:866:in `scheme='
```

**Comment by Holek** [comment]
so, full disclosure from my project. We use Cucumber, Pusher, and WebMock, which uses Addressable.

* Webmock uses Addressable to match addresses to return good mocks, great,
* Pusher tries to call real requests at some times in Cucumber,
* to mitigate that we installed [pusher-fake](https://github.com/tristandunn/pusher-fake), which runs it's own Pusher-like service on a different port. Great, that works.

So, webmock checks mocked URLs with and without scheme (so it can mock both http and https):
* It results in pusher-fake URLs becoming something along:
** `http://127.0.0.1:1234/events/...`, which gets a proper check in addressable,
** `127.0.0.1:1234/events/...`, which blows up on `scheme=`, because it thinks `127.0.0.1` is a scheme, `1234` is host...

**Comment by Holek** [comment]
Even further analysis shows that it only happens for IP addresses, hostnames work fine:

```
irb> Addressable::Template.new("google.com").match "localhost:80/event"
=> nil
irb> Addressable::Template.new("http://google.com").match "localhost:80/event"
=> nil
```

**Comment by sporkmonger** [comment]
So the problem you're having is that you're not actually passing valid URIs to the `match` method. You need to prefix those values with a scheme component or first call `heuristic_parse` on the right hand side of your expression to convert a string that kinda-sort-looks-like-it-might-be-a-URI-but-isn't into an actual URI.

i.e. Do this:

```ruby
Addressable::Template.new("http://google.com").match(
  Addressable::URI.heuristic_parse("127.0.0.1:80/event")
)
```
