### ISSUE TITLE
InvalidURIError on Addressable::URI.escape('http://')

### ISSUE THREAD

**Issue by supremebeing7** [sporkmonger/addressable#216]
When I run `Addressable::URI.escape("http://")`, I get this error:

    Addressable::URI::InvalidURIError: Absolute URI missing hierarchical segment: 'http://'

However, when I run `Addressable::URI.escape("http:/")`, I get no error, and it just returns "http:/"

This seems weird behavior to me. I don't particularly care when escaping whether the URL is missing segments, I just want to invalid characters escaped. 

Is this intended behavior? If not, I can try to put together a PR to fix.

**Comment by sporkmonger** [comment]
This is intended behavior. A double slash indicates an authority segment, while a single slash indicates a path (which is the "hierarchical segment"). Generally Addressable will try to avoid raising errors, but there are a few compositions of URIs that would essentially have a contradictory or illogical meaning, and the former case is one of those while the latter technically is not. This logic generally makes more sense if you replace `"http"` with some other URI scheme.
