### ISSUE TITLE
Ability to set `origin`

### ISSUE THREAD

**Issue by sandstrom** [sporkmonger/addressable#218]
This library is awesome :boat: 

A small wish is the ability to set `origin`, for symmetry.

Retrieving origin works:
```ruby
uri = Addressable::URI.new(:scheme => 'https', :host => 'google.com')
uri.origin #=> "https://google.com"
```

It would be nice if one could set it too:

```ruby
uri = Addressable::URI.new(:origin => 'https://google.com:8080')
uri.port #=> 8080
uri.hostname #=> "google.com"
uri.origin #=> "https://google.com:8080"
```

**Comment by sporkmonger** [comment]
Implemented in b250f422e8e9a026cdc34362320a6b5e197f7f8f.

**Comment by sandstrom** [comment]
Awesome! :boat:

**Comment by sandstrom** [comment]
Friendly ping @sporkmonger 😄

**Comment by dentarg** [comment]
@sandstrom I think it's best to open a new issue about it

**Comment by sandstrom** [comment]
@dentarg Alright, I've opened a new issue here https://github.com/sporkmonger/addressable/issues/272 🇸🇪
