### ISSUE TITLE
Mismatch between libidn and pure Ruby punycode implementation

### ISSUE THREAD

**Issue by dentarg** [sporkmonger/addressable#219]
[with libidn / idn-ruby gem](https://github.com/dentarg/gists/blob/master/gists/addressable-546a/libidn/Gemfile.lock) no exception (seems like a valid URL)

```ruby
[6] pry(main)> Addressable::URI.parse("http://xn--zckp1cyg1.sblo.jp/").display_uri
=> #<Addressable::URI:0x3ff9cf027390 URI:http://xn--zckp1cyg1.sblo.jp/>
```

[without](https://github.com/dentarg/gists/blob/master/gists/addressable-546a/rubyidn/Gemfile.lock) idn-ruby gem, exception is raised

```ruby
[6] pry(main)> Addressable::URI.parse("http://xn--zckp1cyg1.sblo.jp/").display_uri
Addressable::IDNA::PunycodeBadInput: Input is invalid.
from /Users/dentarg/.gem/ruby/2.2.3/gems/addressable-2.4.0/lib/addressable/idna/pure.rb:562:in `punycode_decode'
```

Who to trust?

**Comment by sporkmonger** [comment]
Unfortunately, in this case, the error is correct, which makes resolution difficult. This may be a downstream bug in libidn.

**Comment by sporkmonger** [comment]
That said, this is probably a very good test case.

**Comment by sporkmonger** [comment]
And just to be sure this wasn't a result of the 2.4.0 release yesterday, I did confirm that it happens in both 2.3.8 and 2.4.0.

**Comment by sporkmonger** [comment]
If we ignored the bad decode, the result you'd get would be: "http://ゎパチスロ.sblo.jp/"

**Comment by dentarg** [comment]
I played around with libidn:

```
$ idn --idna-to-unicode xn--zckp1cyg1
xn--zckp1cyg1

$ idn --idna-to-unicode xn--rksmrgs-5wao1o
räksmörgås

$ idn --punycode-decode zckp1cyg1
idn: punycode_decode: Invalid input

$ idn --punycode-decode rksmrgs-5wao1o
räksmörgås
```

```
$ idn --version
idn (GNU Libidn) 1.32
Copyright (C) 2015 Simon Josefsson.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Simon Josefsson.
```

Bug in libidn or should addressable use [`punycode_decode`](https://github.com/sporkmonger/addressable/blob/addressable-2.4.0/lib/addressable/idna/native.rb#L27-L29) in some cases?

**Comment by sporkmonger** [comment]
@jas4711 pointed out to me that RFC 3490 says that `toUnicode` should never fail, so my earlier comment was incorrect. It _is_ a bad input, but the exception should be caught and the input returned in the case of failure.

**Comment by walro** [comment]
> @jas4711 pointed out to me that RFC 3490 says that toUnicode should never fail, so my earlier comment was incorrect. It is a bad input, but the exception should be caught and the input returned in the case of failure.

Just to make sure that I understood correctly, do you propose that the "pure" implementation should behave as the "native" implementation, i.e., for bad input it will return the original string rather than a `Addressable::IDNA::PunycodeBadInput` error when calling `#display_uri`? If so, I think that would be a good change. :-)

**Comment by sporkmonger** [comment]
Closed by 295d7baec1281976434e9061b8065979b3f38c83.

**Comment by sporkmonger** [comment]
@walro Yes, that what 295d7baec1281976434e9061b8065979b3f38c83 does.

**Comment by dentarg** [comment]
thank you @sporkmonger for the fix :-)

**Comment by dentarg** [comment]
@sporkmonger anything we can help with to get a release with 295d7ba?

**Comment by dentarg** [comment]
@sporkmonger just wondering if it's possible to make a new release with the fix done here?
