### ISSUE TITLE
user@domain.ext detect as Invalid URI after 2.4.0

### ISSUE THREAD

**Issue by envygeeks** [sporkmonger/addressable#221]
Originally reported at: https://github.com/travis-ci/travis.rb/issues/342
Commit that breaks Travis CLI: https://github.com/sporkmonger/addressable/commit/8cc24d9139f6138a48fa1fb068df7bc1e845ec95

/cc @ptoomey3 

```
System
Ruby:                     Ruby 2.2.3-p173
Operating System:         Ubuntu 14.04
RubyGems:                 RubyGems 2.5.0

CLI
Version:                  1.8.0
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2015-12-08 13:08:19 -0600

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "envygeeks"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

Last Exception
An error occurred running `travis encrypt`:
    Addressable::URI::InvalidURIError: Invalid scheme format: git@github.com
        from /usr/local/lib/ruby/gems/2.2.0/gems/addressable-2.4.0/lib/addressable/uri.rb:867:in `scheme='
        from /usr/local/lib/ruby/gems/2.2.0/gems/addressable-2.4.0/lib/addressable/uri.rb:795:in `block in initialize'
        from /usr/local/lib/ruby/gems/2.2.0/gems/addressable-2.4.0/lib/addressable/uri.rb:2302:in `call'
        from /usr/local/lib/ruby/gems/2.2.0/gems/addressable-2.4.0/lib/addressable/uri.rb:2302:in `defer_validation'
        from /usr/local/lib/ruby/gems/2.2.0/gems/addressable-2.4.0/lib/addressable/uri.rb:792:in `initialize'
        from /usr/local/lib/ruby/gems/2.2.0/gems/addressable-2.4.0/lib/addressable/uri.rb:135:in `new'
        from /usr/local/lib/ruby/gems/2.2.0/gems/addressable-2.4.0/lib/addressable/uri.rb:135:in `parse'
        from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.8.0/lib/travis/cli/repo_command.rb:75:in `detect_slug'
        from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.8.0/lib/travis/cli/repo_command.rb:60:in `find_slug'
        from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.8.0/lib/travis/cli/repo_command.rb:21:in `setup'
        from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.8.0/lib/travis/cli/command.rb:197:in `execute'
        from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.8.0/lib/travis/cli.rb:64:in `run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.8.0/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'
```

**Comment by ptoomey3** [comment]
It seems strange that it is trying to set `git@github.com` as the scheme. I wonder what the authority is set to in this case.

**Comment by ptoomey3** [comment]
It seems the scheme validation is correct in so far as `git@github.com` is an invalid scheme.

**Comment by envygeeks** [comment]
That's gonna be a hard bug to find if I'm honest, you surfaced a bug for sure when you made that change but tracking down where it happens might turn out to be a bit of a pain if the file size has any bearing on the scale of hardness in the tracking.

**Comment by ptoomey3** [comment]
This actually appears to be a Travis issue and not an issue with `Addressable`. In short, Travis is trying to use `Addressable` to parse scp style URLs. More details in https://github.com/travis-ci/travis.rb/issues/342#issuecomment-164642011.

**Comment by sporkmonger** [comment]
Yup, scp-style "URLs" are _not_ URLs and are explicitly out-of-scope of what Addressable 2.x tries to parse. That could maybe change for Addressable 3.x due to the way it can alter behavior for subclasses, but with everything happening in a single super class and SCP-like pseudo-URLs being sufficiently different in syntax, it would be unlike to try to take that functionality in 2.x. One thing we should be abundantly clear about: This is **not** a URL: "git@github.com:sporkmonger/addressable.git" It has all the component semantic concepts of a URL (username, host, path, etc), but it is not a URL.

Unfortunately, Addressable 3.x is also vapor-ware. I basically need to take a vacation and work on nothing else for a month if it's ever going to get a release.
