### ISSUE TITLE
Cannot match any URI which includes a callback url

### ISSUE THREAD

**Issue by nippysaurus** [sporkmonger/addressable#222]
I need to match a url which includes a callback in the querystring, but any time there is a querystring parameter which looks like a url everything stops working.

For example this does work:

```
template = Addressable::Template.new('{scheme}://{host}{/path*}{?querystring*}')
uri = Addressable::URI.parse("https://example.com?callback=xxxxxxx")
p template.extract(uri)
```

> {"scheme"=>"https", "host"=>"example.com", "path"=>nil, "querystring"=>{"callback"=>"xxxxx"}}

But this does not:

```
template = Addressable::Template.new('{scheme}://{host}{/path*}{?querystring*}')
uri = Addressable::URI.parse("https://example.com?callback=http://example.com/callback")
p template.extract(uri)
```

> nil

I would have at least thought maybe the callback url was parsed instead of the main one (as it should match the template as well) but this does not seem to be the case.

**Comment by sporkmonger** [comment]
```ruby
uri = Addressable::URI.parse("https://example.com?callback=http%3A%2F%2Fexample.com%2Fcallback")
#<Addressable::URI:0x3fc96d0f785c URI:https://example.com?callback=http%3A%2F%2Fexample.com%2Fcallback>
```
