### ISSUE TITLE
Inability to create template url using Addressable::URI

### ISSUE THREAD

**Issue by mib32** [sporkmonger/addressable#230]
I want to construct uri with template this way:

```
Addressable::URI.parse(BASE_DOMAIN).tap do |res|
  res.query_values = {
    p: "{sid}"
  }
end.to_s
```

But i get roughly "example.com/?p=%5dsid%5b" instead of "example.com/?p={sid}" which is unsuitable for later addressable template rendering.

I typically gsub it or do res.query += "&p={sid}", is it possible to do it prettier, or is it something that you think should be done? Thanks.

**Comment by Mifrill** [comment]
@mib32  how about this?:
```
irb(main):018:0> Addressable::URI.parse("http://google.com").tap { |res| res.query = "p={sid}" }.to_s
=> "http://google.com?p={sid}"

```

**Comment by dentarg** [comment]
See https://github.com/sporkmonger/addressable/issues/334#issuecomment-460789394
