### ISSUE TITLE
equivalent of URI.extract?

### ISSUE THREAD

**Issue by epinault** [sporkmonger/addressable#231]
Is there an equivalent in your library of http://ruby-doc.org/stdlib-2.3.0/libdoc/uri/rdoc/URI.html#method-c-extract-label-Synopsis? 

So far I am running in issues with URI.parse not handling unicode properly in the URL (getting bad URI with http://www.motortrend.com/uploads/sites/5/2016/02/Wolfgang-Du%CC%88rheimer.jpg) , forcing me to move to addressable . I would rather use one or the other library, rather than mixing it in..

**Comment by dentarg** [comment]
@epinault if you want you could take a look at https://github.com/twingly/twingly-url which is a wrapper around addressable and has a [`extract_valid_urls`](https://github.com/twingly/twingly-url/blob/v4.0.0/lib/twingly/url/utilities.rb) method

a little heads-up though, we don't hesitate to break the API between major versions (we do our best to follow semver)

**Comment by epinault** [comment]
Sounds good ! thanks!
