### ISSUE TITLE
unescaped HTML in query values

### ISSUE THREAD

**Issue by willhall88** [sporkmonger/addressable#242]
Had an issue where a url with unescaped HTML was being accepted into the query value. 
This caused an issue when the url was then rebuilt with extra queries merged as the order was sorted resulting in the queries being bad:
`?&amp;a=...`

E.g.
Input URL: `example.com?string=foo&amp;another=bar`
resulting in `uri.query_values => {"string"=>"foo", "amp;another"=>"bar"}`
when new params added the returned url looks like: 
`example.com?amp%3Banother=bar&string=foo&...`

Pull Request to follow shortly to fix this..
`uri.query_values => {"string"=>"foo", "another"=>"bar"}`
`example.com?another=bar&string=foo&...`

**Comment by sporkmonger** [comment]
See PR. This is not an issue in Addressable.
