### ISSUE TITLE
Backslashes are accepted in userinfo and host

### ISSUE THREAD

**Issue by clayton-shopify** [sporkmonger/addressable#246]
Addressable accepts backslashes in both the userinfo and host fields even though RFC 3986 does not allow that. Browsers (at least Chrome and Firefox) correct the backslash to a forward slash, and so Addressable comes to a different conclusion than a browser about what the hostname is:
```
irb(main):001:0> require 'addressable/uri'
=> true
irb(main):002:0> Addressable::URI.parse("http://evil.example\\@good.example/").host
=> "good.example"
irb(main):003:0> Addressable::URI.parse("http://evil.example\\.good.example/").host
=> "evil.example\\.good.example"
```
This makes it difficult to use Addressable to validate the hostname of a URL.

**Comment by sporkmonger** [comment]
I think it's reasonable here to replace backslashes with forward slashes in a hostname during normalization.

**Comment by sporkmonger** [comment]
Alternatively I could see an argument for percent encoding backslashes. A hostname should only contain `unreserved` or `sub-delims`, of which a backslash is neither. Everything else is supposed to be percent encoded.

**Comment by sporkmonger** [comment]
Usually the code in Addressable that tries to mimic browsers is in `heuristic_parse` rather than `normalize`.
