### ISSUE TITLE
Absolute URI missing hierarchical segment

### ISSUE THREAD

**Issue by foxeshavedens** [sporkmonger/addressable#248]
I am working on a forked project, which uses addressable. However, whenever I tried to run the rails server locally, I consistently get this error message, which stops me:

Absolute URI missing hierarchical segment: 'http://:9200' (Addressable::URI::InvalidURIError) 

Any guesses why this is happening? Where does addressable get the URI "http://:9200" from, and how can I change it? What should I change it to? (If I'm asking the wrong questions, please advise on that as well!) Thanks

**Comment by dentarg** [comment]
@foxeshavedens I guess the problem has something to with (the configuration of) your rails project, and nothing to do with addressable. I'm afraid you have to seek help elsewhere.

**Comment by foxeshavedens** [comment]
Okay, got it. Any tips on what I should ask or look for?

**Comment by sporkmonger** [comment]
This sounds to me like a client library for elasticsearch maybe that's internally using Addressable. You probably have configured the client in a way that omits the hostname for your elastic search server. Perhaps you assumed that it would default to localhost if it was omitted? It's definitely not a problem with Addressable, however: `http://:9200` is indeed an invalid URI.
