### ISSUE TITLE
Suggestion: Path segment extraction / replacement

### ISSUE THREAD

**Issue by Justin-Maxwell** [sporkmonger/addressable#264]
Would it be feasible/sensible to have an array construct for path segments like:

``` ruby
u= Addressable::URI.parse('https://example.com/abc/def/ghi')
puts u.path.length # 3 
u.path[0] == 'abc' # true
u.path[1] == 'def' # true

u.path[0]= 'xyz'
puts u.path # '/xyz/def/ghi'

u.path[1]= ''
puts u.path # '/xyz/ghi'
puts u.path.length # 2

u.path[0]= 'uvw/xyx' 
puts u.path # '/uvw/xyz/ghi'
puts u.path.length # 3

u.path[0]= '/abc/'
puts u.path # '/abc/xyz/ghi'

u.path[2]= 'ghi/'
puts u.path # '/abc/xyz/ghi/'

u.path[2]= 'ghi'
puts u.path # '/abc/xyz/ghi'
```

or is there something that does this already, that I've missed?

nb: not this exactly, since it would break any existing code using path[n] (to get char n from path-string)

**Comment by sporkmonger** [comment]
I don't feel this would be sufficiently beneficial to warrant implementation. First off, you wouldn't be able to use the same property name as `path`, as you mentioned, which absolutely would have to continue to remain a `String` for backwards compatibility.  Second, while I'm totally on-board with TIMTOWTDI in most cases, keep in mind that you still have to resolve everything down to a `String` when you're done, and this would open all kinds of complex new edge cases. For example:

```
u.path = ''
u.path_segments[0] = '/abc'
u.path_segments[2] = 'xyz/ghi'
```

Now what is `u.path` set to? Is this an array index exception? If so, on which line? If it's not an exception, how would you implement in a way where that's actually the case? Honestly, I couldn't even hazard a guess as to what the result would be or should be.

Finally, I struggle to think of any use-case that isn't already trivially solved by calling `split` on the path yourself. And optionally making a subsequent `join` call and the assigning the path back. And considering that not all URIs are hierarchical to begin with as well, making split semantics inconsistent across URI schemes, I'm going to go with "neither feasible nor sensible" I'm afraid.

I don't mean the above criticism, BTW, to imply "your idea is bad and you should feel bad". Just trying to walk you through why it's not a good idea.
