### ISSUE TITLE
Spaces allowed in path for `Addressable::URI#parse`

### ISSUE THREAD

**Issue by singpolyma-shopify** [sporkmonger/addressable#269]
`Addressable::URI.parse("https://example.com/v3/ ")` does not throw an exception, even though the URI is invalid.

**Comment by dentarg** [comment]
Interestingly both `.heuristic_parse` and `#normalize` removes the trailing space.

```ruby
irb(main):006:0> Addressable::URI.heuristic_parse("https://example.com/v3/ ")
=> #<Addressable::URI:0x3fc9141856b0 URI:https://example.com/v3/>
```

```ruby
irb(main):003:0> Addressable::URI.parse("https://example.com/v3/ ").normalize
=> #<Addressable::URI:0x3fc9141ac260 URI:https://example.com/v3/>
```

Both keep the space if it isn't trailing

```ruby
irb(main):012:0> Addressable::URI.parse("https://example.com/v3/ foo")
=> #<Addressable::URI:0x3fc914159470 URI:https://example.com/v3/ foo>

irb(main):013:0> Addressable::URI.heuristic_parse("https://example.com/v3/ foo")
=> #<Addressable::URI:0x3fc91414c860 URI:https://example.com/v3/ foo>
```

And encodes it when normalized 

```ruby
irb(main):004:0> Addressable::URI.parse("https://example.com/v3/ foo").normalize
=> #<Addressable::URI:0x3fc91419dc9c URI:https://example.com/v3/%20foo>

irb(main):010:0> Addressable::URI.heuristic_parse("https://example.com/v3/ foo").normalize
=> #<Addressable::URI:0x3fc914169bf4 URI:https://example.com/v3/%20foo>
```

(Examples from Addressable 2.5.0)

**Comment by Mifrill** [comment]
@singpolyma-shopify  is this still actual?, it seems like there is not should expect exception

**Comment by singpolyma-shopify** [comment]
@Mifrill problem still exists on 2.5.2, just tested

**Comment by Mifrill** [comment]
@singpolyma-shopify  if I understand correctly you are expecting a exception here: `Addressable::URI.parse("https://example.com/v3/ ")`, coz, `uri` is not valid here, why do you think so?
Please describe in more detail the problem. Thank you

**Comment by singpolyma-shopify** [comment]
@Mifrill because that call does throw `Addressable::URI::InvalidURIError` for other invalid URIs, but not for this one, so I would expect it to throw that exception for all invalid URIs.

**Comment by Mifrill** [comment]
@singpolyma-shopify  great, but the question is why do you think that this uri is invalid?
for example: `https://google.com/%20/` this is valid uri, so what's the difference?

**Comment by singpolyma-shopify** [comment]
sure, `https:/example.com/v3/%20` would also be a valid URL... but spaces are not allowed, they must be encoded

**Comment by dentarg** [comment]
I think we can close this, spaces can be part of the path and changing the behaviour around this in addressable would be breaking for existing users.

I think it is hard for addressable to make the decision here, for example, entering `https://example.com/v3/ ` in Google Chrome, the trailing space is removed. Entering `https://example.com/v3/ foo`, the address bar shows `https://example.com/v3/%20foo`.
