### ISSUE TITLE
Heuristic Parse is not validating

### ISSUE THREAD

**Issue by amed** [sporkmonger/addressable#273]
I am using:

  `addressable (2.5.2)` with `rails (5.1)`
which is originally upgraded from:
  `addressable 2.4.0` with `rails (4.2.6)`
There is validation written with `ActiveModel::Validator`  [Taken from this gist](https://gist.github.com/johnjohndoe/7022109#file-uri_validator-rb-L31)
```
uri_parsed = Addressable::URI.heuristic_parse(link)
```

The validation depends on `InvalidURIError` when parsing the URI, rescue it and do the validation.

```
 > parsed = Addressable::URI.heuristic_parse('bla bla bla')
=> #<Addressable::URI:0x3fdc0f86bb9c URI:bla bla bla> 
```

It was valid rspec test before, and now it is failing due to valid URI.

**Comment by dentarg** [comment]
I don't think there is any issue to solve here.

It sounded like `Addressable::URI::InvalidURIError` was raised for this case with version 2.4.0, but that doesn't seem to be the case:

```ruby
$ bundle exec irb -raddressable/uri
irb(main):001:0> Addressable::VERSION::STRING
=> "2.4.0"
irb(main):002:0> Addressable::URI.heuristic_parse('bla bla bla')
=> #<Addressable::URI:0x3fddba0bd4fc URI:bla bla bla>
irb(main):003:0> Addressable::URI.heuristic_parse('bla bla bla').relative?
=> true
irb(main):004:0> Addressable::URI.parse('bla bla bla')
=> #<Addressable::URI:0x3fddba4529a0 URI:bla bla bla>
irb(main):005:0> Addressable::URI.parse('bla bla bla').relative?
=> true
```

Addressable thinks the URL is relative based on the information given.
