### ISSUE TITLE
Version 2.5.2 requires Ruby >= 2.1 due to dependency on public_suffix

### ISSUE THREAD

**Issue by toddmowen** [sporkmonger/addressable#274]
According to the [rubygems page](https://rubygems.org/gems/addressable/versions/2.5.2), version 2.5.2 should only require Ruby >= 2.0, however because it broadened the dependency on [public_suffix](https://rubygems.org/gems/public_suffix) from `>= 2.0.2, ~> 2.0` in 2.5.1 to `< 4.0, >= 2.0.2`, gem will now try to install [public_suffix 3.0.0](https://rubygems.org/gems/public_suffix/versions/3.0.0), which actually requires Ruby >= 2.1.

In other words, 2.5.2 is a backwards-incompatible change, albeit only for projects still using Ruby 2.0. It thus violates semantic versioning IMHO -- although this might be debatable.

I first reported this here: octokit/octokit.rb#948, after seeing one of my projects fail like this:

```
$ gem install octokit netrc
YAML safe loading is not available. Please upgrade psych to a version that supports safe loading (>= 2.0).
Fetching: multipart-post-2.0.0.gem (100%)
Successfully installed multipart-post-2.0.0
Fetching: faraday-0.13.1.gem (100%)
Successfully installed faraday-0.13.1
Fetching: public_suffix-3.0.0.gem (100%)
ERROR:  Error installing octokit:
	public_suffix requires Ruby version >= 2.1.
```

**Comment by dentarg** [comment]
Hmm, shouldn't rubygems understand that is running on Ruby 2.0 and pick public_suffix 2.0.5?

**Comment by dentarg** [comment]
Bundler figures it out (but I guess that's not much of a help if you don't use bundler).

```
$ cat Gemfile
# frozen_string_literal: true
source "https://rubygems.org"

gem "octokit"

$ ls -ahl
total 16
drwxr-xr-x@  4 dentarg  staff   136B Oct 18 09:48 ./
drwxr-xr-x@ 64 dentarg  staff   2.1K Oct 18 09:47 ../
-rw-r--r--@  1 dentarg  staff     6B Oct 18 09:47 .ruby-version
-rw-r--r--@  1 dentarg  staff    75B Oct 18 09:49 Gemfile

$ ruby -v
ruby 2.0.0p648 (2015-12-16) [x86_64-darwin16.7.0]

$ bundle
The latest bundler is 1.16.0.pre.3, but you are currently running 1.15.4.
To update, run `gem install bundler --pre`
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Rubygems 2.0.14.1 is not threadsafe, so your gems will be installed one at a time. Upgrade to Rubygems 2.1.0 or higher to enable parallel gem installation.
Using public_suffix 2.0.5
Using bundler 1.15.4
Using multipart-post 2.0.0
Fetching addressable 2.5.2
Installing addressable 2.5.2
Using faraday 0.13.1
Fetching sawyer 0.8.1
Installing sawyer 0.8.1
Fetching octokit 4.7.0
Installing octokit 4.7.0
Bundle complete! 1 Gemfile dependency, 7 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

**Comment by dentarg** [comment]
> shouldn't rubygems understand that is running on Ruby 2.0 and pick public_suffix 2.0.5?

Apparently not: https://github.com/rubygems/rubygems/issues/968

**Comment by dentarg** [comment]
> 2.5.2 is a backwards-incompatible change, albeit only for projects still using Ruby 2.0. 

Only for projects not using Bundler? :-)

> It thus violates semantic versioning IMHO -- although this might be debatable

Yeah, I don't think it does

**Comment by toddmowen** [comment]
Thanks for looking into this. By the way, I've upgraded to Ruby 2.2, so I'm not directly affected by this anymore, but I thought it was worth reporting for the sake of others.

> Bundler figures it out

Not sure what you mean -- the output above indicates that even bundler picked addressable 2.5.2, even though it's not compatible with the `ruby` binary.

**Comment by toddmowen** [comment]
Oops, sorry about the comment above, yes I can see that bundler picks the compatible version of public_suffix.

I agree that semantic versioning is not broken; the stated dependency range `public_sufix < 4.0, >= 2.0.2` is only one constraint, which the dependency resolver should take into account along with other constaints.

Closing this issue.
