### ISSUE TITLE
Unused variable: startercc

### ISSUE THREAD

**Issue by sudo-nice** [sporkmonger/addressable#285]
Hello!
If I run the script file:
```
#!/usr/bin/ruby2.5 -w

require 'addressable'
```
the warning appears:

`/var/lib/gems/2.5.0/gems/addressable-2.5.2/lib/addressable/idna/pure.rb:154: warning: assigned but unused variable - startercc`

**Comment by dentarg** [comment]
This is fixed by pull request https://github.com/sporkmonger/addressable/pull/270

**Comment by sudo-nice** [comment]
I see, thanks.
