### ISSUE TITLE
[proposal] encryption?

### ISSUE THREAD

**Issue by timoschilling** [sporkmonger/addressable#287]
Does it make sense to add a method for example named `encryption?` which tells you about that the protocol uses a encryption.

Examples:
```ruby
Addressable::URI.parse('https://example.com').encryption? # => true
Addressable::URI.parse('http://example.com').encryption? # => false
```

It could be implemented like this:
```ruby
PORT_MAPPING = {
  "http" => false,
  "https" => true,
  "ssh" => true,
  "ftp" => false,
  "sftp" => true
  ...
}

def encryption?
  PORT_MAPPING[self.scheme.strip.downcase] if self.scheme
end
# similar to `default_port`
```

This feature would be very useful if you use `Addressable` together with `Net::Http`.
```ruby
uri = Addressable::URI.parse('https://example.com')

Net::HTTP.start(uri.host, uri.inferred_port, use_ssl: (uri.schema == 'https'))
# vs.
Net::HTTP.start(uri.host, uri.inferred_port, use_ssl: uri.encryption?)
```

I would be happy to write a PR for this feature!

**Comment by sporkmonger** [comment]
There are quite a few protocols w/ URIs for which this wouldn't be true/false, such as LDAP. I also strongly suspect that this could lead to security issues.
