### ISSUE TITLE
the method for redefinition top-level domain `tld=`

### ISSUE THREAD

**Issue by Mifrill** [sporkmonger/addressable#289]
it will be very convenient to use `tld=` to redefine the top-level domain, similar to redefine url path

```
require "addressable/uri"
=> true

url = Addressable::URI.parse("http://example.com/path/to/resource/")

# Example for path (method path=)

url.path
=> "/path/to/resource/"

url.to_s
=> "http://example.com/path/to/resource/"

url.path="redefenitioned/path/to/some/resource"
=> "redefenitioned/path/to/some/resource"

url.to_s
=> "http://example.com/redefenitioned/path/to/some/resource"

# Example for tld (expected method tld=)
irb(main):005:0> url.tld
=> "com"

irb(main):012:0> url.tld="uk"
NoMethodError: undefined method `tld=' for #<Addressable::URI:0x1e68a90>
Did you mean?  tld
        from (irb):12
        from C:/Ruby23/bin/irb.cmd:19:in `<main>'

# Got error, but expected:
=> "uk"
url.to_s
=> "http://example.uk/redefenitioned/path/to/some/resource"
```

Please, do the same method, for tld (tld=), it's convenient. Thank you

**Comment by Mifrill** [comment]
To solve this problem can be very simple. But i think, this method will be very useful, thanks

```
irb(main):019:0> url.to_s.sub(/#{url.tld}/, "uk")
=> "http://example.uk/redefenitioned/path/to/some/resource"
```

**Comment by dentarg** [comment]
> The solution can be very simple

Beware that `sub` doesn't work as expected when the TLD is part of the domain name:

```ruby
$ irb -raddressable/uri
irb(main):001:0> url = Addressable::URI.parse("http://comrade.com/path/to/resource/")
=> #<Addressable::URI:0x3fcf4d1130e4 URI:http://comrade.com/path/to/resource/>
irb(main):002:0> new_url = Addressable::URI.parse(url.to_s.sub(/#{url.tld}/, "uk"))
=> #<Addressable::URI:0x3fcf4c8c5e50 URI:http://ukrade.com/path/to/resource/>
```

> but now the url is a string, and not Addressable object, and we can no longer work with it using Addressable object's methods

Just parse the string again to get an Addressable::URI :-)

**Comment by Mifrill** [comment]
@dentarg 
thanks, it really is, I just gave an example that instead of re-parse, or other way, it's much more convenient to do this method in the gem itself.
I'm talking about what it would be like to do this method, just like the `path=`
