### ISSUE TITLE
URI::site method undefined

### ISSUE THREAD

**Issue by Convincible** [sporkmonger/addressable#299]
On ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux] I am getting the error `undefined method 'site' for #<URI::HTTP http://localhost:4000>`. Other methods like `host` etc. seem to work fine.

**Comment by dentarg** [comment]
@Convincible that doesn't look like an issue with addressable

Looks like you are calling `#site` on the wrong object

```ruby
$ irb -raddressable/uri -ruri
irb(main):001:0> Addressable::URI.parse("http://localhost:4000").site
=> "http://localhost:4000"
irb(main):002:0> URI.parse("http://localhost:4000").site
NoMethodError: undefined method `site' for #<URI::HTTP http://localhost:4000>
	from (irb):2
	from /Users/dentarg/.rubies/ruby-2.4.2/bin/irb:11:in `<main>'
```

**Comment by Convincible** [comment]
Thanks. Actually I was doing this:

```ruby
uri = Addressable::URI::parse(@input)
puts uri.site
```

I think the local variable `uri` was clashing somehow with the `URI` class? As this seems to have fixed itself after changing the local variable name.

**Comment by dentarg** [comment]
No, I don't think so. `uri` is not the same as `URI` in Ruby. I think your object, `@input`, happened to be an instance of [`URI::HTTP`](https://ruby-doc.org/stdlib-2.5.1/libdoc/uri/rdoc/URI/HTTP.html).

**Comment by Convincible** [comment]
I agree, that's what I thought! @input was just a string, which happened to be a URL, i.e. `"http://localhost:4000"`. Maybe it will remain a mystery... at any rate it now seems to be working.
