### ISSUE TITLE
Ruby 2.4 compatibility

### ISSUE THREAD

**Issue by voltechs** [sporkmonger/addressable#308]
Should this line say `0.class`?

https://github.com/sporkmonger/addressable/blob/dcc505ce02beccb99b9f5ea8ac7526a21afc733c/spec/addressable/uri_spec.rb#L4807

**Comment by dentarg** [comment]
I think we can just change it to `Integer`, [as `Integer` exist in Ruby 2.0.0](https://ruby-doc.org/core-2.0.0/Integer.html), the lowest version we test with.

If you (or someone else) wants to send a PR for it, the following lines can also be updated:

https://github.com/sporkmonger/addressable/blob/0e640ca64ab461d43bcf0d5515adc8f63da76872/lib/addressable/template.rb#L197

https://github.com/sporkmonger/addressable/blob/0e640ca64ab461d43bcf0d5515adc8f63da76872/lib/addressable/template.rb#L153
