### ISSUE TITLE
Applications must always unescape user and password

### ISSUE THREAD

**Issue by nbibler** [sporkmonger/addressable#322]
I saw some discussion around this in #42. Is it the intended behavior that Addressable does not automatically unescape user and password values?

```ruby
>> uri = Addressable::URI.parse('http://test.url/')
=> #<Addressable::URI:0x3ff17d8a7628 URI:http://test.url/>
>> uri.user = 'us+er'
=> "us+er"
>> uri.password = 'pas wo/d='
=> "pas wo/d="
>> uri.normalize!
=> #<Addressable::URI:0x3ff17d8a7628 URI:http://us%2Ber:pas%20wo%2Fd%3D@test.url/>
>> uri.user
=> "us%2Ber"
>> uri.password
=> "pas%20wo%2Fd%3D"
```

This would functionally require that applications using Addressable should always unescape the user and password values before use (for example Faraday has a [`basic_auth` middleware](https://github.com/lostisland/faraday#authentication) which need to be populated with these values at construction):

```ruby
>> uri = Addressable::URI.parse('http://us%2Ber:pas%20wo%2Fd%3D@test.url/')
=> #<Addressable::URI:0x3ff17d504020 URI:http://us%2Ber:pas%20wo%2Fd%3D@test.url/>
>> user = CGI.unescape(uri.user)
=> "us+er"
>> password = CGI.unescape(uri.password)
=> "pas wo/d="
```

Simply taking the `uri.user` or `uri.password` will not work, since they are escaped and incorrect if used directly.

Part of this question stems from inconsistency with Addressable's behavior around `query_values` which are unescaped when queried:

```ruby
>> uri = Addressable::URI.parse('https://host.url/?test=b%3Dd')
=> #<Addressable::URI:0x3ff17d4c0460 URI:https://host.url/?test=b%3Dd>
>> uri.query_values
=> {"test"=>"b=d"}
>> uri.query_values['test']
=> "b=d"
```

**Comment by sporkmonger** [comment]
`query_values` is sort of special though as it's more of a view on top of `query`. I'm more concerned about consistency with more typical accessors like `query` or `path`.

**Comment by nbibler** [comment]
I can certainly see that. Would it make sense to introduce a view on top of user and password?

It's just less than ideal that everywhere I'm using Addressable in an application I must also `require 'cgi'` and `CGI.escape(addressable.user)` (for example).

I'm not a fan of the naming, but something similar to `user_value` and `password_value`? Although, it feels like a slippery slope.

**Comment by dentarg** [comment]
@nbibler is this a problem that needs solving really? (in addressable?) I read #42 (hadn't seen it before, it was interesting), and I think you have accepted that you need to encode user and password to be able to parse URLs with it with Addressable

but why not let Addressable unescape it? no need to require CGI 

```ruby
$ irb -r addressable/uri
irb(main):001:0> uri = Addressable::URI.parse('http://us%2Ber:pas%20wo%2Fd%3D@test.url/')
=> #<Addressable::URI:0x3fc9d303f41c URI:http://us%2Ber:pas%20wo%2Fd%3D@test.url/>
irb(main):002:0> Addressable::URI.unescape(uri.user)
=> "us+er"
irb(main):003:0> Addressable::URI.unescape(uri.password)
=> "pas wo/d="
```

**Comment by nbibler** [comment]
Ahh. I didn't realize there was a public `unescape` on URI. That would remove the need for requiring/using CGI, agreed! Thanks!

**Comment by nbibler** [comment]
As a side note, using the `Addressable::URI.unescape` implementation saves me from needing `nil` checks everywhere. 👍 

```
>> require 'addressable/uri'
=> true
>> require 'cgi'
=> true
>> Addressable::URI.unescape(nil)
=> nil
>> CGI.unescape(nil)
TypeError (no implicit conversion of nil into String)
```
