### ISSUE TITLE
not possible to expand variable names containing hyphen

### ISSUE THREAD

**Issue by WickyNilliams** [sporkmonger/addressable#330]
I've looked through the spec and can't see anything forbidding hyphens in variable names (see: Section 2.2).

This snippet demonstrates the issue

```rb
template = Addressable::Template.new "/foo{?ab}"
template.expand(ab: true).to_s
# => "/foo?ab=true"

template = Addressable::Template.new "/foo{?a-b}"
template.expand("a-b": true).to_s
# => "/foo{?a-b}"
```

Am I missing something? Thanks in advance

**Comment by therabidbanana** [comment]
[Section 2.3](https://tools.ietf.org/html/rfc6570#section-2.3) defines the allowed set of characters for a varspec (the word used in the RFC for each variable with optional modifier in curly braces), which I believe applies here - variable names can have periods or underscores, but not hyphens (unless percent encoded). I think that applies to your examples and is likely why the expansion isn’t working:

```
variable-list =  varspec *( "," varspec )
     varspec       =  varname [ modifier-level4 ]
     varname       =  varchar *( ["."] varchar )
     varchar       =  ALPHA / DIGIT / "_" / pct-encoded
```

It’s honestly strange to me that the unreserved set additionally includes hyphens, which is used for the expanded values (this is why your last example works), but I didn’t write the spec - just tried to implement it :)

**Comment by WickyNilliams** [comment]
Thanks @therabidbanana, somehow completely missed that section. It's a weird limitation for sure. But I guess I can live with my workaround above. Thanks again
