### ISSUE TITLE
Feature: Add config to add empty brackets

### ISSUE THREAD

**Issue by rafaeldev** [sporkmonger/addressable#331]
Hi everyone!

I have a context with Rails API where i need send data via query parameter as like that:
`http://host/to/endpoint?items[]=foo&items[]=bar`

Today when pass a array to `#query_values` it reproduces it:
`http://host/to/endpoint?items=foo&items=bar`

I can't found a way to do that with actual code.

I think so we need make thing configurable on that block:
https://github.com/sporkmonger/addressable/blob/473d9b5b76f8c4ee77e92af5eb02c457e74192d3/lib/addressable/uri.rb#L1722-L1729

See ya!

**Comment by dentarg** [comment]
From https://github.com/sporkmonger/addressable/issues/282

> The model of using `[]` suffixes has no support in a standards-based context and will not be supported by Addressable.
