### ISSUE TITLE
URI#merge() not copying path or query?

### ISSUE THREAD

**Issue by krainboltgreene** [sporkmonger/addressable#336]
I'm running v2.6.0 and I get some strange results with `#merge()`. Consider the following:

```
incoming = Addressable::URI.parse("https://gateway.example.com:80/v1/accounts?fields=name")

target = Addressable::URI.parse("http://resources:3000")

outgoing = incoming.merge(target)
```

I would expect this output:

```
http://resources:3000/v1/accounts?fields=name
```

However the result is:

```
http://resources:3000
```

What am I doing wrong? I suspect it's that the `:path` property of this uri is being parsed as `""` which has a present key, but not a real value.

Further, I also expected that if a value was `nil` in the left then the right would be used. For example:

```
incoming = Addressable::URI.parse("https://gateway.example.com:80/v1/accounts?fields=name")

target = Addressable::URI.parse("http://resources")

outgoing = incoming.merge(target)
```

I would expect:

```
http://resources:80/v1/accounts?fields=name
```

But that doesn't appear to be the case.

These two cases cause me to have to write:

```
incoming = Addressable::URI.parse("https://gateway.example.com:82/v1/accounts?fields=name")

target = Addressable::URI.parse("http://resources:80")

outgoing = incoming.merge(target.to_hash.transform_values(&:presence).compact)
```

Which necessitates ActiveSupport.

**Comment by dentarg** [comment]
I don't think you should call `#merge` the way you do it, see the documentation:

https://github.com/sporkmonger/addressable/blob/a0e06dbfc91ea820a111b2db30795088c907c29e/lib/addressable/uri.rb#L1971-L1980

I think this is why your last example works better.

Note: This is just a quick reply and I haven't tried to used `#merge` myself. We can re-open if there seems to be an actual bug.

You can see [some examples in the specs](https://github.com/sporkmonger/addressable/blob/c37d71cceb4a02beff99ce7fca9e35f5e094099b/spec/addressable/uri_spec.rb#L4045-L4049).

**Comment by Nakilon** [comment]
I still don't get it:
```none
irb> Addressable::URI.parse("a/b?c=d").merge({"e"=>"f"}).to_s
=> "a/b?c=d"
```
