### ISSUE TITLE
Update public_suffix to 4.0.0

### ISSUE THREAD

**Issue by Medvezo** [sporkmonger/addressable#346]
https://github.com/weppos/publicsuffix-ruby/blob/master/CHANGELOG.md

**Comment by ddfreyne** [comment]
FYI: The only change in `public_suffix` 4.0 appears to be dropping support for Ruby 2.3.

**Comment by sporkmonger** [comment]
If it drops support for 2.3, I'm inclined to just change from `"< 4.0"` to `"< 5.0"`, assuming Addressable passes tests against all versions in between.
