### ISSUE TITLE
Fix broken builds

### ISSUE THREAD

**Issue by dentarg** [sporkmonger/addressable#348]
As seen on https://travis-ci.org/sporkmonger/addressable/builds/551279504 the tests for old rubies fail, due to missing idn library, when `idn-ruby` is to be installed for these versions:

https://github.com/sporkmonger/addressable/blob/60e119e12624475870e23af1b79905b037ebc48f/Gemfile#L32

https://github.com/sporkmonger/addressable/blob/60e119e12624475870e23af1b79905b037ebc48f/gemfiles/Gemfile.public_suffix_2#L34

The builds on Travis CI [now run on xenial](https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment) (Ubuntu 16.04) and not trusty (Ubuntu 14.04), and I guess that is the reason for the idn library missing.

The jruby failures seems to be https://github.com/rvm/rvm/issues/4720

**Comment by ashmaroli** [comment]
There seems to be two lines commented out in the Travis config:
https://github.com/sporkmonger/addressable/blob/60e119e12624475870e23af1b79905b037ebc48f/.travis.yml#L27-L28
