### ISSUE TITLE
override params issue

### ISSUE THREAD

**Issue by JulienItard** [sporkmonger/addressable#352]
Hello,

i have `uri = Addressable::URI.parse("test.com?foo=bar")` so `uri.query_values` => {"foo"=>"bar"}
i want to override foo param so i do 
`uri.query_values = uri.query_values.merge({"foo"=>"bar2"})` 
now `uri.query_values` => {"foo"=>"bar2"}

but if i do `uri.query` it returns `foo=bar&foo=bar2`. Why it doesnt override it ?

Thanks for help !

**Comment by dentarg** [comment]
It is because addressable allows the following behaviour, quote from https://en.wikipedia.org/wiki/Query_string#Web_forms

>While there is no definitive standard, most web frameworks allow multiple values to be associated with a single field (e.g. `field1=value1&field1=value2&field2=value3`).

(Related to https://github.com/sporkmonger/addressable/issues/282)
