### ISSUE TITLE
Net::HTTP builds invalid request from Addressable::URI making server to throw 500

### ISSUE THREAD

**Issue by Nakilon** [sporkmonger/addressable#373]
When I request `https://v.redd.it/1mpabcjw1m841` I get a Location redirect to `https://www.reddit.com/video/1mpabcjw1m841`. Then when I use the Ruby's Net::HTTP debug feature like this:
```ruby
          http.set_debug_output( Object.new.tap do |obj|
            obj.instance_eval do
              def << msg
                @@buffer ||= "[Net::HTTP debug] "
                @@buffer.concat msg
                @@buffer = @@buffer[0...997] + "..." if @@buffer.size > 500
                return unless @@buffer.end_with? ?\n
                puts @@buffer.sub ?\n, "  "
                @@buffer = nil
              end
            end
          end )
```
I see the next request:
```
[Net::HTTP debug] <- "HEAD /video/1mpabcjw1m841 HTTP/1.1\r\nAccept: */*\r\nUser-Agent: Ruby\r\nHost: www.reddit.com\r\nConnection: close\r\n\r\n"
```
Now the server that I'm requesting to has a cyrillic path in Location so I get the `URI must be ascii only` error on the next redirect -- that's why I want to use your gem because AFAIK it works better with other alphabets. But it seems to build the request incorrectly:
```
[Net::HTTP debug] <- "HEAD https://www.reddit.com/video/1mpabcjw1m841 HTTP/1.1\r\nAccept: */*\r\nUser-Agent: Ruby\r\nConnection: close\r\nHost: www.reddit.com\r\n\r\n"
```
I assume the path by HTTP standard should not include domain and this is what makes Reddit to throw:
```
[Net::HTTP debug] -> "HTTP/1.1 500 Domain Not Found\r\n" 
```
You can see that this:
```ruby
new_uri = URI.join request.uri.to_s, response["location"]
p new_uri.path
p Net::HTTP::Head.new(new_uri).path.to_s
new_uri = Addressable::URI.join request.uri.to_s, response["location"]
p new_uri.path
p Net::HTTP::Head.new(new_uri).path.to_s
```
outputs:
```
"/video/1mpabcjw1m841"
"/video/1mpabcjw1m841"
"/video/1mpabcjw1m841"
"https://www.reddit.com/video/1mpabcjw1m841"
```
So I suppose there is a bug somewhere that `Net::HTTP` requests (at least HEAD) can't construct from `Addressable::URI`correctly:
```ruby
p Net::HTTP::Head.new(URI("https://www.reddit.com/video/1mpabcjw1m841")).path.to_s
p Net::HTTP::Head.new(Addressable::URI.parse("https://www.reddit.com/video/1mpabcjw1m841")).path.to_s
```
```
"/video/1mpabcjw1m841"
"https://www.reddit.com/video/1mpabcjw1m841"
```
UPD: If I use Addressable only to escape the Location and not to build the whole uri:
```ruby
new_uri = URI.join request.uri.to_s,  Addressable::URI.escape(response["location"])
```
then I get the:
```
[Net::HTTP debug] <- "HEAD /r/Pikabu/comments/ejjvfu/%D1%83...%D0%B7/ HTTP/1.1\r\nAccept: */*\r\nUser-Agent: Ruby\r\nHost: www.reddit.com\r\nCookie: edgebucket=...\r\nConnection: close\r\n\r\n"  
[Net::HTTP debug] -> "HTTP/1.1 502 Bad Gateway\r\n"  
```
that is an error too but is probably irrelevant and can't be ignored because Reddit API is just buggy. My issue is about the string part after the `HEAD` in request that I assume to be built incorrectly. (or is it ok by HTTP standard and is again a Reddit's fault?)

**Comment by dentarg** [comment]
I don't think there's any problem with Addressable here. It looks like you are escaping the URL correctly with Addressable:

```ruby
$ ruby -raddressable/uri -e 'p Addressable::URI.escape("https://www.reddit.com/r/Pikabu/comments/ejjvfu/упражнение_финских_спасателей_как_пролезть_через/")'
"https://www.reddit.com/r/Pikabu/comments/ejjvfu/%D1%83%D0%BF%D1%80%D0%B0%D0%B6%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5_%D1%84%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D1%85_%D1%81%D0%BF%D0%B0%D1%81%D0%B0%D1%82%D0%B5%D0%BB%D0%B5%D0%B9_%D0%BA%D0%B0%D0%BA_%D0%BF%D1%80%D0%BE%D0%BB%D0%B5%D0%B7%D1%82%D1%8C_%D1%87%D0%B5%D1%80%D0%B5%D0%B7/"
```

This matches the escaping that `curl` does:

```
$ curl -v -s -o /dev/null -L -w "\n\nfinal location: %{url_effective}\nhttp status: %{http_code}" https://v.redd.it/1mpabcjw1m841 2>&1 | grep -E 'location:|http status:'
< location: https://www.reddit.com/video/1mpabcjw1m841
< location: https://www.reddit.com/r/Pikabu/comments/ejjvfu/упражнение_финских_спасателей_как_пролезть_через/
final location: https://www.reddit.com/r/Pikabu/comments/ejjvfu/%d1%83%d0%bf%d1%80%d0%b0%d0%b6%d0%bd%d0%b5%d0%bd%d0%b8%d0%b5_%d1%84%d0%b8%d0%bd%d1%81%d0%ba%d0%b8%d1%85_%d1%81%d0%bf%d0%b0%d1%81%d0%b0%d1%82%d0%b5%d0%bb%d0%b5%d0%b9_%d0%ba%d0%b0%d0%ba_%d0%bf%d1%80%d0%be%d0%bb%d0%b5%d0%b7%d1%82%d1%8c_%d1%87%d0%b5%d1%80%d0%b5%d0%b7/
http status: 200
```

As you wrote, Reddit doesn't always gives you 200 OK responses. In fact, I also got a couple 502 Bad Gateway responses from Reddit when I played around with curl.

---

FYI, as an alternative to `net/http`, check out https://github.com/httprb/http, it's really easy to use:

```ruby
$ ruby -rhttp -e 'p HTTP.follow.get("https://v.redd.it/1mpabcjw1m841")'
#<HTTP::Response/1.1 200 OK ... >
```

**Comment by Nakilon** [comment]
The issue is not in escaping. It happens before it gets to the cyrillic address.
The request built with `URI` is this:
```
HEAD /video/1mpabcjw1m841
```
When it's built with `Addessable::URI` it is:
```
HEAD https://www.reddit.com/video/1mpabcjw1m841
```
where instead of a path it sends the whole uri.

**Comment by dentarg** [comment]
What is the problem with Addressable? I don't understand.

**Comment by Nakilon** [comment]
The `Net::HTTP::Head.new` accepts the `URI` object to buld a request. The `Addressable::URI.join` and `Addressable::URI.parse` produce it in incompatible way that makes it send an absolute URI instead of a path. According to 5.1.2 of https://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html the use of a path is more common while handling an absolute URI here was a recommended server behaviour for future ersions of HTTP and is in practice unsupported at least by Reddit as I can see as I tested it hundred of times while debugging to create this issue. While the `Addressable` makes `Net::HTTP` to send an absolute URI the default `URI` library was making it to send a path that is in practice more compatible.

**Comment by Nakilon** [comment]
@dentarg what's the current status of this issue?

**Comment by dentarg** [comment]
@Nakilon It is closed. I don't think compatibility between `Addressable::URI` and `URI` is a goal of the Addressable project. You have to solve your problem in your own code.

**Comment by dentarg** [comment]
@Nakilon Also, you haven't properly described what you want from Addressable, when reporting a bug, please do it like this, with code examples (and what versions of Addressable and Ruby you are using).

* What I did (code using Addressable)
* What I expected
* What actually happened
