### ISSUE TITLE
normalized_path full-width chars japanese 

### ISSUE THREAD

**Issue by ignacio-chiazzo** [sporkmonger/addressable#375]
Using the `normalized_path` method turns the Japanese `１` into `1`. This also happens for ２ -> 2 etc. (More about half-width and half-width characters and numbers [here](https://tokyofromtheinside.com/filling-up-registration-forms-japan/ ))

```ruby
 url = "http://a.com/%EF%BC%91" # http://a.com/１ 
Addressable::URI.parse(url).normalized_path # "/1"
```

```
[152] pry(main)> url = "http://a.com/%EF%BC%91" # http://a.com/１ 
=> "http://a.com/%EF%BC%91"
[153] pry(main)> Addressable::URI.parse(url).normalized_path # 
=> "/1"
[154] pry(main)> 

```

Looks like it was done on purpose on the lines https://github.com/sporkmonger/addressable/blob/7311daa2166e2f15d897ee9c9c3cf656e17135af/lib/addressable/uri.rb#L1537-L1541

Am I missing something from the [RFC](https://tools.ietf.org/html/rfc3986#section-6)?

**Comment by dentarg** [comment]
Addressable is using NFKC normalization, so this is expected.

See https://github.com/sporkmonger/addressable/issues/8#issuecomment-26674048 and other issues like https://github.com/sporkmonger/addressable/issues/217 and https://github.com/sporkmonger/addressable/issues/325.

https://towardsdatascience.com/difference-between-nfd-nfc-nfkd-and-nfkc-explained-with-python-code-e2631f96ae6c has some examples for different forms of normalization.
