### ISSUE TITLE
stack level too deep (SystemStackError), how to trace or fix ?

### ISSUE THREAD

**Issue by nirajan-fleetpanda** [sporkmonger/addressable#380]
ruby-2.5.7/gems/addressable-2.7.0/lib/addressable/idna/pure.rb:305:in `lookup_unicode_composition'
/Users/nirazan/.rvm/gems/ruby-2.5.7/gems/addressable-2.7.0/lib/addressable/idna/pure.rb:305:in `hash': stack level too deep (SystemStackError)

ruby: 2.5.7
rails: 5.2.0

**Comment by dentarg** [comment]
How can the issue be reproduced?

**Comment by nirajan-fleetpanda** [comment]
Looks like it's new relic issue , uninstall the gem and now I'm not getting same issue anymore
