### ISSUE TITLE
Remove rack-mount test case

### ISSUE THREAD

**Issue by voxik** [sporkmonger/addressable#382]
I wonder what is the purpose of the rack-mount test case, when rack-mount was deprecated upstream ages ago and the repository was even removed. I see, that you have your own fork, presumably to keep the tests passing, but is there really any benefit?

**Comment by dentarg** [comment]
Looks like it was added in https://github.com/sporkmonger/addressable/pull/191

The addressable project isn't very active these days, so there's probably a bunch of things that made sense a while ago that doesn't today. 

I've never used rack-mount myself, but if someone would be using that fork of it today, dropping it would be a breaking change for them. But you are probably right, these days the usage of [that gem](https://rubygems.org/gems/rack-mount) is probably very low.

**Comment by sporkmonger** [comment]
Yeah, I'd be completely fine dropping the test case.

**Comment by sporkmonger** [comment]
Re: activity, I've pretty much moved entirely over to Go, so I'm only checking in occasionally to do a bit of maintenance here and there. It's a pretty stable codebase and has been for years, and the specs don't change much, so it doesn't require a lot.

**Comment by dentarg** [comment]
It was dropped in https://github.com/sporkmonger/addressable/commit/c04233f5b75b6f4d9053cb4c62382831615776de
