### ISSUE TITLE
Should #parse('example.com') populate path or host with 'example.com' ?

### ISSUE THREAD

**Issue by mattscilipoti** [sporkmonger/addressable#388]
In my app, users are asked to input a URL. I have been asked to help users that do not include a scheme/protocol, by assigning 'https'. I expected #parse('example.com') to assign 'example.com' to :host. Instead, it is assigned to :path. Is this a bug?

```
uri = Addressable::URI.parse('example.com')
uri.host => nil
uri.path => 'example.com'
```
Addressable::VERSION::STRING
"2.6.0"

**Comment by mattscilipoti** [comment]
Interestingly, if I assign a scheme, it outputs this:
```
uri.scheme = 'https'
uri.to_s => "https:example.com"
```

**Comment by dentarg** [comment]
URL can be relative, that's why you are seeing what you are seeing with `#parse`

You probably want to use `#heuristic_parse`:

```ruby
$ irb -raddressable/uri
irb(main):001:0> uri = Addressable::URI.heuristic_parse('example.com')
=> #<Addressable::URI:0x3fff2489d0ec URI:http://example.com>
irb(main):002:0> uri.host
=> "example.com"
irb(main):003:0> uri.scheme
=> "http"
irb(main):004:0> uri.scheme = 'https'
=> "https"
irb(main):005:0> uri.to_s
=> "https://example.com"
irb(main):006:0> Addressable::VERSION::STRING
=> "2.7.0"
```
