### ISSUE TITLE
normalize_component changes unexpectedly UTF-8 characters

### ISSUE THREAD

**Issue by s-tkt** [sporkmonger/addressable#400]
This is not bug report but a simple question.
normalize_component changes "！＃＄" into "!#$".
Not only "！＃＄" but also any UTF-8 characters which have corresponding ASCII characters are changed to ASCII characters.
This conversion is just a trouble to UTF-8 user like me.
Could you tell me how I can escape from this conversion.

**Comment by dentarg** [comment]
Can you share some real code that shows your issue?

**Comment by s-tkt** [comment]
Like this.

```
require 'addressable/uri'

path = '！＄＆１２３ＡＢＣ'
path = Addressable::URI.normalize_component path, Addressable::URI::CharacterClasses::PATH
print path + "\n"
```

**Comment by dentarg** [comment]
See https://github.com/sporkmonger/addressable/issues/8#issuecomment-26674048
