### ISSUE TITLE
Encoding an IPv6 address raises an exception

### ISSUE THREAD

**Issue by davidtaylorhq** [sporkmonger/addressable#402]
Calling `URI.encode` with an IPv6 literal host raises an exception:

```
[1] pry(main)> Addressable::URI.encode("http://[fe80::200:f8ff:fe21:67cf]/")
Addressable::URI::InvalidURIError: Invalid port number: "67cf]"
from /usr/local/lib/ruby/gems/2.6.0/gems/addressable-2.7.0/lib/addressable/uri.rb:1409:in `port='
```
I believe the output here should be `http://[fe80::200:f8ff:fe21:67cf]/`. RFC3986 defines square brackets as [reserved within the authority component](https://tools.ietf.org/html/rfc3986#appendix-D.1), and as such they should not be percent-encoded.

The root cause appears to be https://github.com/sporkmonger/addressable/blob/f839fb28344567c792e148d7a74c529748455d11/lib/addressable/uri.rb#L611-L612

Adding `"\\[\\]"` to `CharacterClasses::AUTHORITY` appears to resolve the issue. The example above returns the expected result.

Square brackets are already included in `CharacterClasses::HOST`. Given that `HOST` is a component of `AUTHORITY` I would naively expect all `HOST` reservations to also be present in `AUTHORITY`, but there may be some nuance I'm missing here.

Very happy to open a PR with that fix, or investigate alternative solutions if needed.

**Comment by sporkmonger** [comment]
Yeah, I think you're probably correct in this assessment. A fix for this probably warrants a minor version rev.
