### ISSUE TITLE
URI.unencode does not separate URIs into components

### ISSUE THREAD

**Issue by snicky** [sporkmonger/addressable#405]
This may not be a real issue, but rather a design decision. I'm curious why `URI.unencode` doesn't separate URIs into components as defined in https://tools.ietf.org/html/rfc3986#section-2.4

`encode` breaks URIs into components:
https://github.com/sporkmonger/addressable/blob/f839fb28344567c792e148d7a74c529748455d11/lib/addressable/uri.rb#L608-L619

but `unencode` does not:
https://github.com/sporkmonger/addressable/blob/f839fb28344567c792e148d7a74c529748455d11/lib/addressable/uri.rb#L467-L471

**Comment by dentarg** [comment]
This is my understanding from reading the source.

When we encode, certain characters are not encoded, depending on what part of the URI we are encoding:

https://github.com/sporkmonger/addressable/blob/f839fb28344567c792e148d7a74c529748455d11/lib/addressable/uri.rb#L346-L351

We don't need to unencode what we didn't encode, so there's only one method to unencode:

https://github.com/sporkmonger/addressable/blob/f839fb28344567c792e148d7a74c529748455d11/lib/addressable/uri.rb#L480-L484
