### ISSUE TITLE
Why did it "№" turn into this "No"

### ISSUE THREAD

**Issue by kewogc** [sporkmonger/addressable#415]
```
URI.unescape "%E2%84%96"
=> "№"

Addressable::URI.unescape "%E2%84%96"
=> "№"

Addressable::URI.parse("%E2%84%96").normalize
=> "No"
```
Whats is happen? Why did it "№" turn into this "No"

**Comment by dentarg** [comment]
See https://github.com/sporkmonger/addressable/issues/375#issuecomment-574401692

Its happening because you asked for (Unicode) normalization. You can try it elsewhere if you want, e.g. https://dencode.com/en/string/unicode-normalization
