### ISSUE TITLE
Addressable license compatibility with libidn

### ISSUE THREAD

**Issue by ojab** [sporkmonger/addressable#432]
I created [an issue in `ruby-idn` repo](https://github.com/deepfryed/idn-ruby/issues/8), but since I don't use this gem directly, makes sense to copy here, I guess, since addressable depends on libidn [in some configurations].

[libidn COPYING](https://git.savannah.gnu.org/gitweb/?p=libidn.git;a=blob;f=COPYING;h=ef77cc839a02aa2377f82914e44f33c23eca5842;hb=HEAD) says 
```
The source code for the C library (libidn.a or libidn.so), the C#
library (Libidn.dll) and the Java library (libidn-*.jar) are licensed
under the terms of either the GNU General Public License version 2.0
or later (see the file COPYINGv2) or the GNU Lesser General Public
License version 3.0 or later (see the file COPYING.LESSERv3), or both
in parallel as here.

The author of the Java library has agreed to also distribute it under
the Apache License Version 2.0 (see the file java/LICENSE-2.0).
```
and [libidn2](https://gitlab.com/libidn/libidn2/-/blob/master/COPYING) says
```
The source code for the C library (libidn2.a or libidn.so) are
licensed under the terms of either the GNU General Public License
version 2.0 or later (see the file COPYINGv2) or the GNU Lesser
General Public License version 3.0 or later (see the file
COPYING.LESSERv3), or both in parallel as here.
```
We cannot depend on GPL libarary for sure and (IANAL) [ASF puts LGPL in category X](https://www.apache.org/legal/resolved.html#category-x), which means that it couldn't be used in apache-licensed project. Googling ([example](https://github.com/mabe02/lanterna/issues/415)) confirms this.

Looks like this gem couldn't be licensed under Apache License 2.0.

**Comment by dentarg** [comment]
Closing this as the `idn-ruby` repo closed that issue: https://github.com/deepfryed/idn-ruby/issues/8#issuecomment-960346874, also, you can use Addressable without using libidn.
