### ISSUE TITLE
warning: character class has duplicated range

### ISSUE THREAD

**Issue by ukolovda** [sporkmonger/addressable#437]
I've got the error
"warning: character class has duplicated range"

I found that Addressable::URI::CharacterClasses::AUTHORITY  has redundant colon:
```
PCHAR = UNRESERVED + SUB_DELIMS + "\\:\\@"
...
AUTHORITY = PCHAR + "\\[\\:\\]"
```

See https://github.com/sporkmonger/addressable/blob/f3fb80c0adb60ce7012c36e5d3714b037a280b06/lib/addressable/uri.rb#L51

Ruby 3.0.2 give this warning.

**Comment by dentarg** [comment]
Solved by https://github.com/sporkmonger/addressable/pull/438
