### ISSUE TITLE
Tests failure with idn-ruby 0.1.3

### ISSUE THREAD

**Issue by ukolovda** [sporkmonger/addressable#442]
After update `idn-ruby` to 0.1.3 `IDN::Stringprep.nfkc_normalize` returns nil for invalid utf-8 parameter.
I append workaround, see https://github.com/sporkmonger/addressable/pull/441

**Comment by dentarg** [comment]
Related to https://github.com/deepfryed/idn-ruby/issues/9

**Comment by dentarg** [comment]
Should be resolved once idn-ruby 0.1.4 is released, see https://github.com/deepfryed/idn-ruby/pull/10#issuecomment-956782876 and https://github.com/deepfryed/idn-ruby/commit/3b4374f613f4301b3288a9727ee9e620145e2f15
