### ISSUE TITLE
Semantic versioning broken in 2.8.0

### ISSUE THREAD

**Issue by runephilosof** [sporkmonger/addressable#456]
2.8.0 broke semantic versioning
Changelog contains
> dropping support for Ruby 2.0 and 2.1
> adding Ruby 3.0 compatibility for development tasks
> drop support for rack-mount and remove Addressable::Template#generate

It should have been 3.0

How should it be fixed?
1. Release 2.8.0 as version 3.0.
2. Yanking the version from Rubygems seems the appropriate action, but it can break other projects' deployment pipelines...

I don't know the best approach in these circumstances.

**Comment by dentarg** [comment]
While I think you can drop versions without major bump (a topic for lengthy discussions) it looks like the gemspec wasn't updated to reflect this, and that's unfortunate 

Yanking is out of the question as it would be breaking for everyone 

What isn't working on 2.0 and 2.1? 

There hasn't been that many changes so what could be done is to restore compatibility in 2.8.1 and then drop it correctly in the next version

**Comment by dentarg** [comment]
I've updated the gemspec to indicate Ruby >= 2.2 now. I'll be closing this as there's been no info supplied about what isn't working with Ruby 2.0/2.1.
