### ISSUE TITLE
Dependabot couldn't find a Gemfile

### ISSUE THREAD

**Issue by moussatat** [sporkmonger/addressable#479]
Hi
I am confused about the warning I get in regard to my basic project using the site generator Docusaurus.
Why is dependabot 
- asking for a Gemfile  to add "addressable version 2.8.0"
- sending "[Regular Expression Denial of Service in Addressable templates" severe security warning, 
when my project there is no gemfile anyway ?
Do I dismiss this ?

**Comment by dentarg** [comment]
there's a security vulnerability in addressable <2.8.0

Apply the update to 2.8.0 (or 2.8.1) to address it

**Comment by moussatat** [comment]
I generated everything using docusaurus, there is no ruby and I shouldn't be using gems. 
There must be something wrong in your alert.

**Comment by dentarg** [comment]
The alert is from GitHub, please contact them.
