### ISSUE TITLE
 Invalid scheme format for ssh URL

### ISSUE THREAD

**Issue by gyorgygabor** [sporkmonger/addressable#483]
Hello,

I need to parse an ssh repo url that starts like this:
git@ssh.dev.azure.com:v1/project/path

I tried this:
` git_repository_name = Addressable::URI.parse(git_url).path.split('/').last
` 
And i am getting the following error:
`.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/addressable-2.8.1/lib/addressable/uri.rb:917:in `scheme=': Invalid scheme format: 'git@ssh.dev.azure.com' (Addressable::URI::InvalidURIError)
`

Could someone help me?

**Comment by dentarg** [comment]
I think your URL are missing scheme, try adding `ssh://` to the start

**Comment by gyorgygabor** [comment]
Thank you for the answer. Unfortunately, it does not work, I get the following error:
`/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/addressable-2.8.1/lib/addressable/uri.rb:1421:in `port=': Invalid port number: "v1" (Addressable::URI::InvalidURIError)
`

Although, my URL is valid as it's described here:
https://learn.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops

 So, I am not sure if I should manipulate my url or parse it manually maybe.

**Comment by dentarg** [comment]
Ah okay, you can't parse SSH URIs with Addressable, they are not following the RFCs implemented by Addressable, from https://unix.stackexchange.com/questions/75668/why-doesnt-the-ssh-command-follow-rfc-on-uri

> `ssh` predates the more general URI format ([1998](http://en.wikipedia.org/wiki/Uniform_resource_identifier)) by several years (1995 IIRC).

You may have luck with using some of the individual methods for parsing components, I don't know. There might be other libraries out there doing what you want. Feel free to share if you find any.
