### ISSUE TITLE
Is it intended that `normalized_path` destroys the trailing dot when it's the only char?

### ISSUE THREAD

**Issue by Nakilon** [sporkmonger/addressable#484]
```
irb(main):014:0> Addressable::URI.heuristic_parse("http://example.com/a").normalized_path
=> "/a"
irb(main):015:0> Addressable::URI.heuristic_parse("http://example.com/a.").normalized_path
=> "/a."
irb(main):016:0> Addressable::URI.heuristic_parse("http://example.com/.").normalized_path
=> "/"
```
Related: https://github.com/bblimke/webmock/issues/893

**Comment by dentarg** [comment]
Yes

I believe this document supports that: https://www.rfc-editor.org/rfc/rfc3986#section-5.4.2

Also, when I enter `https://example.com/.` in Google Chrome it is turned into `https://example.com/`, I see not request to `https://example.com/.`
