### ISSUE TITLE
Equivalent of `URI.regexp(schemes)`?

### ISSUE THREAD

**Issue by postmodern** [sporkmonger/addressable#493]
Is there an equivalent of [URI.regexp](https://rubydoc.info/stdlib/uri/URI#regexp-class_method) which can take an array of URI schemes and produce a regexp that only matches URIs with those schemes? This would help with validating URIs which `Addressable::URI.parse()` can parse, but `URI.parse` cannot.

**Comment by postmodern** [comment]
Normally I would have asked this question in GitHub Discussions to avoid cluttering the Issue tracker, but GitHub Discussions are not currently enabled on this project.

**Comment by dentarg** [comment]
I don't think there is, but I haven't read all the source code in detail.

**Comment by dentarg** [comment]
There's `Addressable::URI::URIREGEX`

https://github.com/sporkmonger/addressable/blob/1fdd676753fb2f44c9d7e0953c97c3e6becfb36a/lib/addressable/uri.rb#L122-L123

but as the source code points out, it doesn't do everything

https://github.com/sporkmonger/addressable/blob/1fdd676753fb2f44c9d7e0953c97c3e6becfb36a/lib/addressable/uri.rb#L134-L136

**Comment by postmodern** [comment]
@dentarg I saw `URIREGEX`, but it does not match _specific_ schemes (ex: `URI.regexp(['http', 'https'])`). Instead it will match *all* schemes, which is not what I want.

```ruby
regex = URI.regexp(['http', 'https'])
"http://example.com" =~ regex
=> 0
"https://example.com" =~ regex
=> 0
"foo://example.com" =~ regex
=> nil
"foo://example.com" =~ Addressable::URI::URIREGEX
=> 0
```

`URIREGEX` is not an equivalent to `URI.regexp(schemes)`.
