### ISSUE TITLE
Any version after 2.8.1 causes errors in our test suite coming from addressable.

### ISSUE THREAD

**Issue by danielnolan** [sporkmonger/addressable#506]
The change in 2.8.2 that sets the query to [NONE](https://github.com/sporkmonger/addressable/commit/fde3e54ae1bccf6ce93570f469f3da0966acb6be#diff-1d4fc0b240535c07d5db04a59efa2942b22cf3c32256daaf5144d407c3051341R2587) seems to be causing issues with postrank-uri gem in our app. Any version of addressable after 2.8.1 and we start seeing these failures. 
```
# --- Caused by: ---
          # TypeError:
          #   Can't convert Object into String.
          #   /Users/danielnolan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/addressable-2.8.4/lib/addressable/uri.rb:1638:in `query='
  ```
          
```
# /Users/danielnolan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/addressable-2.8.4/lib/addressable/uri.rb:1638:in `query='
          # /Users/danielnolan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/addressable-2.8.4/lib/addressable/uri.rb:853:in `block in initialize'
          # /Users/danielnolan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/addressable-2.8.4/lib/addressable/uri.rb:2394:in `defer_validation'
          # /Users/danielnolan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/addressable-2.8.4/lib/addressable/uri.rb:842:in `initialize'
          # /Users/danielnolan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/addressable-2.8.4/lib/addressable/uri.rb:2170:in `new'
          # /Users/danielnolan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/addressable-2.8.4/lib/addressable/uri.rb:2170:in `normalize'
          # /Users/danielnolan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/webmock-3.18.1/lib/webmock/util/uri.rb:20:in `block in <class:URI>'
          # /Users/danielnolan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/webmock-3.18.1/lib/webmock/util/uri.rb:33:in `normalize_uri'
          # /Users/danielnolan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/webmock-3.18.1/lib/webmock/request_signature.rb:10:in `initialize'
          # /Users/danielnolan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/webmock-3.18.1/lib/webmock/http_lib_adapters/net_http.rb:267:in `new'
          # /Users/danielnolan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/webmock-3.18.1/lib/webmock/http_lib_adapters/net_http.rb:267:in `request_signature_from_request'
          # /Users/danielnolan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/webmock-3.18.1/lib/webmock/http_lib_adapters/net_http.rb:70:in `request'
```

**Comment by dentarg** [comment]
Can you post the code that reproduce the problem? Please use the last way version

**Comment by rickyc** [comment]
I was able to do it in Rails console using this code.

```rb
RestClient.get("google.com")
TypeError: Can't convert Object into String.
from .gem/ruby/3.1.3/gems/addressable-2.8.4/lib/addressable/uri.rb:1636:in `query='
```

**Comment by danielnolan** [comment]
It seems to be any rails project that has this gem included https://github.com/postrank-labs/postrank-uri
here is an app to reproduce https://github.com/danielnolan/addressable_bug all you should have to do is bundle and run rspec

**Comment by dentarg** [comment]
Please provide code using only Addressable that reproduces the issue, thanks

**Comment by danielnolan** [comment]
@dentarg Not sure it's an issue in addressable by itself, but going from 2.8.1 to 2.8.2 or greater shouldn't introduce breaking changes in gems that depend on addressable right? I would maybe expect breaking changes going from 2.8.x to 2.9, or 2.8 to 3.x, but not 2.8.1 to 2.8.2, as patch versions should be backwards compatible.

**Comment by dentarg** [comment]
There was no intention to introduce breaking changes in a patch version. This looks like a bug. In order to address the bug we need to know how to reproduce it. 

Can you or someone else look into what the gems in the Rails repro are doing with addressable that causes this?

**Comment by danielnolan** [comment]
Well after looking into the postrank-uri gem source it looks like it monkey patches the domain and normalized_query methods of the Addressable::URI class. So I'm not sure it actually is a bug in Addressable. 
https://github.com/postrank-labs/postrank-uri/blob/master/lib/postrank-uri.rb#L8-L31
