### ISSUE TITLE
Unsafe concurrent Hash access

### ISSUE THREAD

**Issue by eregon** [sporkmonger/addressable#514]
It happens for SEQUENCE_UPCASED_PERCENT_ENCODING_TABLE and SEQUENCE_ENCODING_TABLE
See https://github.com/oracle/truffleruby/issues/3166#issuecomment-1640352210

This happens on TruffleRuby and possibly on JRuby.
On CRuby the error will not happen due to the GIL.
On CRuby it may still cause duplicate computation and assignment for the same key.

A good solution would be to use a Concurrent::Map from `concurrent-ruby` instead of raw `Hash` there.
And the same for SEQUENCE_ENCODING_TABLE just above.
(as a note, this is the correct pattern: https://github.com/ruby-concurrency/concurrent-ruby/issues/970)
Then it's fast on CRuby and is thread-safe and scales on no-GVL Rubies.

Of course this would add a dependency on  `concurrent-ruby` for this gem.

**Comment by eregon** [comment]
An alternative would be to use a Mutex around all accesses to these global Hash'es.
But that would be slower on CRuby due to the extra Mutex on read, and not scale on no-GVL Rubies.
So performance-wise it's strictly worse than concurrent-ruby for all Rubies.

**Comment by dentarg** [comment]
> It happens for SEQUENCE_UPCASED_PERCENT_ENCODING_TABLE and SEQUENCE_ENCODING_TABLE

Because I looked it up I'll note that those were introduced with https://github.com/sporkmonger/addressable/commit/880b34c6518279cf9450e4af3818e51531db5a69

**Comment by dentarg** [comment]
> A good solution would be to use a Concurrent::Map from `concurrent-ruby` instead of raw `Hash` there

Would that help even before https://github.com/ruby-concurrency/concurrent-ruby/issues/970 is addressed?

**Comment by eregon** [comment]
Yes, the only thing I meant by that link is one should use that `compute_if_absent` pattern to avoid assigning a given key twice.

**Comment by dentarg** [comment]
Right, so the way to address this (with `concurrent-ruby`) is using `Concurrent::Map` and `compute_if_absent` [like this](https://github.com/rails/rails/pull/46536/files)?

**Comment by eregon** [comment]
Yes

**Comment by eregon** [comment]
More comments by @byroot at https://github.com/oracle/truffleruby/issues/3166#issuecomment-1641498276

**Comment by eregon** [comment]
@byroot Any chance you could take a look at this? :)

It'd be good to figure out what's the desired solution for `addressable`.

**Comment by byroot** [comment]
I was quite busy lately. I'll try to find some time to dig into this next week.
