### ISSUE TITLE
feed:http: crashes servers 

### ISSUE THREAD

**Issue by SoniEx2** [sporkmonger/addressable#520]

**Comment by dentarg** [comment]
Is this a real bug report or spam?

**Comment by dentarg** [comment]
You need to explain the issue, please post an example

**Comment by SoniEx2** [comment]
here's an example https://github.com/mastodon/mastodon/blob/main/app/controllers/authorize_interactions_controller.rb (luckily this one only crashes the page, not the whole server)

**Comment by dentarg** [comment]
Please post some example code in this issue demonstrating the issue

**Comment by SoniEx2** [comment]
1. register on mastodon.social
2. login
3. visit https://mastodon.social/authorize_interaction?uri=feed:http://mastodon.social/@Gargron
4. get a 500

sorry we just strongly disagree with "normalizing" `feed:http:` as `http:`.

**Comment by SoniEx2** [comment]
can you deprecate/remove the `feed:http:` -> `http:` conversion.

**Comment by dentarg** [comment]
At least I tried.

**Comment by dentarg** [comment]
Please show how they are a problem. Post a snippet of code using Addressable, demonstrating the problem. Thanks.
