### ISSUE TITLE
Valid domain not parsing

### ISSUE THREAD

**Issue by matthewford** [sporkmonger/addressable#523]
Invalid character in host: '[dean.st](http://dean.st/) '

**Comment by dentarg** [comment]
No problem here 

```
$ ruby -raddressable/uri -e 'p Addressable::VERSION::STRING; p Addressable::URI.parse("dean.st")'
"2.8.5"
#<Addressable::URI:0x3c URI:dean.st>
```

Please provide more information (code reproducing the issue) and we could re-open if it looks like an issue with Addressable.
