### ISSUE TITLE
Addressable::URI.escape method does not escape & properly as path param

### ISSUE THREAD

**Issue by patrickcook28** [sporkmonger/addressable#531]
I am using the `Addressable::URI.escape` method to convert a string to a valid escaped HTTP url. I noticed some odd behavior when `&` is used in the URL as a path param.

For example:
```
url = 'http://website.com/api/vendors/H&M Vendor'

Addressable::URI.escape(url)
=> "http://website.com/api/vendors/H&M%20Vendor"

url = 'http://website.com/api/vendors?code=H&M Vendor'

Addressable::URI.escape(url)
=>"http://website.com/api/vendors?code=H&M%20Vendor"
```

In both circumstances the & was not escaped when it should be. The expected result would have been:
```
http://website.com/api/vendors/H%26M%20Vendor
http://website.com/api/vendors?code=H%26M%20Vendor

```

When using built in libray it returns:
```
ERB::Util.url_encode(url)
=> "http%3A%2F%2Fwebsite.com%2Fapi%2Fvendors%3Fcode%3DH%26M%20Vendor"
```

**Comment by dentarg** [comment]
Unlike other encode/escape methods (like `CGI.escape`, `ERB::Util.url_encode`) `Addressable::URI.escape`/`Addressable::URI.encode` is aware of the full URI: 

https://github.com/sporkmonger/addressable/blob/b136f7d521401b5b88b253ded6537e46505a266a/lib/addressable/uri.rb#L600-L616

...and acts according to the URI standard, where `&` is a reserved character: https://datatracker.ietf.org/doc/html/rfc3986#section-2.2

> The purpose of reserved characters is to provide a set of delimiting characters that are distinguishable from other data within a URI. URIs that differ in the replacement of a reserved character with its corresponding percent-encoded octet are not equivalent.  Percent- encoding a reserved character, or decoding a percent-encoded octet that corresponds to a reserved character, will change how the URI is interpreted by most applications. **Thus, characters in the reserved set are protected from normalization and are therefore safe to be used by scheme-specific and producer-specific algorithms for delimiting data subcomponents within a URI.**

Although a bit clunky, you can encode anything with `Addressable::URI.encode_component` [if you pass another `character_class`](https://github.com/sporkmonger/addressable/blob/b136f7d521401b5b88b253ded6537e46505a266a/lib/addressable/uri.rb#L369-L374):

```ruby
> Addressable::URI.encode_component("&", " ")
=> "%26"
```
