### ISSUE TITLE
query_values regressed with latest release

### ISSUE THREAD

**Issue by crawlik** [sporkmonger/addressable#77]
Hi guys,
According this doc http://addressable.rubyforge.org/api/Addressable/URI.html#query_values-instance_method `query_values` has regressed with latest release.

Here is what get calling it
`
jruby-1.6.2 :001 > require "addressable/uri"
 => true 
jruby-1.6.2 :002 > Addressable::URI.parse(
jruby-1.6.2 :003 >       "?one[two][three][]=four&one[two][three][]=five"
jruby-1.6.2 :004?>   ).query_values
 => {"one[two][three][]"=>"five"} 
`
2.2.8 version returns expected results
`
ruby-1.6.2 :001 >  require "addressable/uri"
 => true 
jruby-1.6.2 :002 >  require "addressable/uri"
 => false 
jruby-1.6.2 :003 > Addressable::URI.parse(
jruby-1.6.2 :004 >       "?one[two][three][]=four&one[two][three][]=five"
jruby-1.6.2 :005?>   ).query_values
 => {"one"=>{"two"=>{"three"=>["four", "five"]}}} 
`

**Comment by krainboltgreene** [comment]
Sorry to dredge this up, but could this possibly be helped by having `Addressable::URI` return a `Addressable::Query` object that can have it's own set of parse logic? For backward compatibility you could make it a Hash-like object.
